import { Inter } from "next/font/google";
import { useRouter } from "next/router";
import Head from "next/head";
import styles from "@/styles/Landing.module.css";
import Logo from "../../components/logo";
import { useState } from "react";
import ProposalCard from "@/components/proposal";
const inter = Inter({ subsets: ["latin"] });

export default function Chama() {
  const [selected, setSelected] = useState("proposals");
  const router = useRouter();
  const { id } = router.query;
  const name = `Chama ${id}`;
  const desc =
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eget ultricies tincidunt, nisl nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl.";
  const members = [
    {
      id: 1,
      name: "User 1",
      address: "0x1234567890",
    },
    {
      id: 2,
      name: "User 2",
      address: "0x1234567890",
    },
    {
      id: 3,
      name: "User 3",
      address: "0x1234567890",
    },
  ];

  const proposals = [
    {
      id: 1,
      name: "Proposal 1",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eget ultricies tincidunt, nisl nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl.",
      creator: "user1",
    },
    {
      id: 2,
      name: "Proposal 2",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eget ultricies tincidunt, nisl nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl.",
      creator: "user2",
    },
    {
      id: 3,
      name: "Proposal 3",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eget ultricies tincidunt, nisl nisl aliquam nisl, eget aliquam nisl nisl sit amet nisl.",
      creator: "user3",
    },
  ];

  return (
    <>
      <Head>
        <title>Chama DAO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Logo />
        <div className={styles.profile}>
          <div className={styles.profile_image}></div>
          <div className={styles.profile_name}>{name}</div>
          <div className={styles.profile_desc}>{desc}</div>
        </div>

        <div className={styles.chama}>
          <div className={styles.header}>
            <div className={styles.search}>
              <input type="text" placeholder="Search" />
            </div>
            <div className={styles.choose}>
              <div
                onClick={() => setSelected("proposals")}
                style={
                  selected == "proposals"
                    ? { borderBottom: "3px solid var(--pinky)" }
                    : { border: "" }
                }
              >
                <b>Proposals</b>
              </div>
              <div
                onClick={() => setSelected("members")}
                style={
                  selected == "members"
                    ? { borderBottom: "3px solid var(--pinky)" }
                    : { border: "" }
                }
              >
                <b>Members</b>
              </div>
            </div>
          </div>
          <div className={styles.mine}>
            {selected == "proposals" ? (
              <div className={styles.proposals}>
                {proposals.map((proposal) => (
                  <ProposalCard
                    key={proposal.id}
                    name={proposal.name}
                    desc={proposal.desc}
                    creator={proposal.creator}
                  />
                ))}
              </div>
            ) : (
              <div className={styles.members}>
                {members.map((member) => (
                  <div className={styles.member} key={member.id}>
                    <div className={styles.member_image}></div>
                    <div className={styles.member_name}>{member.name}</div>
                    <div className={styles.member_address}>
                      {member.address}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
          <div className={styles.all}></div>
        </div>
      </main>
    </>
  );
}
