import Head from "next/head";
import Image from "next/image";
import homeStyles from "@/styles/Home.module.css";
import styles from "@/styles/Create.module.css";
import loginStyle from "@/styles/Login.module.css";
import Logo from "../../components/logo";
import { Inter } from "next/font/google";
import { useState } from "react";
// import cloudinary from "@/utils/cloudinary";

const inter = Inter({ subsets: ["latin"] });

export default function Create() {
  const [file, setFile] = useState(null);
  function handleInput(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const name = (e.currentTarget.name as any).value;
    const description = e.currentTarget.description.value;
    if (!name || !description) return;

    if (file == null) return;

    // // upload image to cloudinary
    // cloudinary.v2.uploader.upload(file, (error, result) => {
    //   console.log(result, error);
    // });


    window.location.assign("/chama/1");
  }
  return (
    <>
      <Head>
        <title>Create Chama</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${homeStyles.main} ${inter.className}`}>
        <Logo />
        <h1 className={styles.title}>Create Chama</h1>

        <div className={styles.form}>
          <form onSubmit={handleInput}>
            <div className={loginStyle.input}>
              <label htmlFor="name">Chama Name</label>
              <input type="text" name="name" id="name" />
              <p>What will you call your chama. The name must be unique</p>
            </div>
            <div className={loginStyle.input}>
              <label htmlFor="decsription">Description</label>
              <textarea name="description" id="description" rows={10} cols={55}/>
              <p>A little about your chama. What does it involve?</p>
            </div>
            {file == null ? (
            <div className={loginStyle.input}>
              <label htmlFor="image">Chama Logo</label>
              <input type="file" name="image" id="image" accept="image/*" onChange={
                (e) => {
                  const file = (e.target.files as any)[0];
                  setFile(file);
                }
              }/>
              <p>
                Upload a logo for your chama to help people identify you easily
              </p>
            </div>):(
              <div className={styles.prev}>
                <Image src={URL.createObjectURL(file)} alt="Chama Logo" width={200} height={200} />
              </div>
            )}
            <div className={loginStyle.input}>
              <p>
                After clicking <b>Create</b>, your chama will be created and it
                will be available on your profile. Click on it to add new
                members and have fun associating.
              </p>
            </div>
            <div className={loginStyle.input}>
              <button type="submit" className={loginStyle.button}>
                Create
              </button>
            </div>
          </form>
        </div>
      </main>
    </>
  );
}
