import Head from "next/head";
import homeStyles from "@/styles/Home.module.css";
import styles from "@/styles/Landing.module.css";
import Logo from "../components/logo";
import { useEffect, useState } from "react";
import { Inter } from "next/font/google";
import ContentCopyIcon from "@mui/icons-material/ContentCopy";
import AddIcon from "@mui/icons-material/Add";
import { Add } from "@mui/icons-material";
import Chama from "../components/chamaCard";
import Link from "next/link";
import { User } from "@/utils/types";

const inter = Inter({ subsets: ["latin"] });

export default function Landing() {
  const [user, setUser] = useState({} as User);
  const [address, setAddress] = useState(null);
  const [selected, setSelected] = useState("mine");

  useEffect(() => {
    const token = localStorage.getItem("token");
    if (token != null) {
      const user = JSON.parse((localStorage.getItem("user") as string));
      setUser(user);
    } else {
      window.location.assign("/signup");
    }
  }, []);

  const chamas_mine = [
    {
      id: 1,
      name: "Community Health Alliance",
      desc: "Community Health Alliance is a non-profit organization dedicated to improving the health and well-being of underserved communities. Our mission is to provide affordable and accessible healthcare services to those who need it the most. We work with local partners and volunteers to educate the community on health and wellness, empower individuals to take control of their health, and inspire positive change.",
      creator: "user1",
    },
    {
      id: 2,
      name: "Environmental Conservation Society",
      desc: "Environmental Conservation Society is a group of like-minded individuals who are passionate about protecting our planet. We work to preserve natural resources, promote sustainable practices, and raise awareness about environmental issues. Our members contribute their time, expertise, and resources to create a better future for our planet and all living beings.",
      creator: "user2",
    },
    {
      id: 3,
      name: "Youth Development Initiative",
      desc: "Youth Development Initiative is a non-profit organization that focuses on empowering young people through education and skill-building. We believe that every young person has the potential to succeed, and we work to provide them with the tools and resources they need to reach their full potential. Our programs include mentorship, job training, and academic support, and we partner with local schools and businesses to create meaningful opportunities for youth.",
      creator: "user3",
    },
    {
      id: 4,
      name: "Women's Empowerment Network",
      desc: "Women's Empowerment Network is a community-based organization that aims to empower women and girls by providing them with the resources, skills, and support they need to achieve their goals. We offer a variety of programs, including leadership development, entrepreneurship training, and financial literacy workshops. Our goal is to create a world where all women have the opportunity to thrive and succeed.",
      creator: "user4",
    },
    // Add more organizations here
  ];


  const chamas_all = [
    {
      id: 1,
      name: "Chama all 1",
      desc: "This is a chama",
      creator: "user1",
    },
    {
      id: 2,
      name: "Chama all 2",
      desc: "This is a chama",
      creator: "user2",
    },
    {
      id: 3,
      name: "Chama all 3",
      desc: "This is a chama",
      creator: "user3",
    },
  ];

  const toUse = selected === "mine" ? chamas_mine : chamas_all;
  return (
    <>
      <Head>
        <title>Chama DAO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Logo />

        <div className={styles.profile}>
          <div className={styles.profile_image}></div>
          <div className={styles.profile_name}>@{user.name}</div>
          <div className={styles.profile_address}>
            {user.address} &r
            <span>
              <ContentCopyIcon
                onClick={(e) => {
                  //increate size of icon using e
                  (e.target as any).style.transition = "all 0.1s ease";
                  (e.target as any).style.fontSize = "2rem";
                  navigator.clipboard.writeText(address as any as string);
                  setTimeout(() => {
                    (e.target as any).style.fontSize = "1.5rem";
                  }, 100);
                }}
              />
            </span>
          </div>

          <div className={styles.create}>
            <Link href="/chama/create">
            <div>
              Create <AddIcon />{" "}
            </div>
            </Link>
          </div>
        </div>

        <div className={styles.chama}>
          <div className={styles.header}>
            <div className={styles.search}>
              <input type="text" placeholder="Search" />
            </div>
            <div className={styles.choose}>
              <div
                onClick={() => setSelected("mine")}
                style={
                  selected == "mine"
                    ? { borderBottom: "3px solid var(--pinky)" }
                    : { border: "" }
                }
              >
                <b>Yours</b>
              </div>
              <div
                onClick={() => setSelected("others")}
                style={
                  selected == "others"
                    ? { borderBottom: "3px solid var(--pinky)" }
                    : { border: "" }
                }
              >
                <b>Others</b>
              </div>
            </div>
          </div>
          <div className={styles.mine}>
            {toUse.map((chama, index) => {
              return (
                <Chama
                  key={index}
                  id={chama.id}
                  name={chama.name}
                  desc={chama.desc}
                  creator={chama.creator}
                />
              );
            })}
          </div>
          <div className={styles.all}></div>
        </div>
      </main>
    </>
  );
}
