import Head from "next/head";
import homeStyles from "@/styles/Home.module.css";
import styles from "@/styles/Landing.module.css";
import Logo from "./components/logo";
import { useEffect, useState } from "react";
import { Inter } from "next/font/google";
import ContentCopyIcon from "@mui/icons-material/ContentCopy";
import AddIcon from '@mui/icons-material/Add';
import { Add } from "@mui/icons-material";

const inter = Inter({ subsets: ["latin"] });

export default function Landing() {
  const [user, setUser] = useState(null);
  const [address, setAddress] = useState(null);

  useEffect(() => {
    const usr = window.localStorage.getItem("user");
    const addr = window.localStorage.getItem("address");
    if (usr && addr) {
      setUser(usr as any);
      setAddress(addr as any);
    } else {
      window.location.assign("/signup");
    }
  }, []);

  return (
    <>
      <Head>
        <title>Chama DAO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Logo />

        <div className={styles.profile}>
          <div className={styles.profile_image}></div>
          <div className={styles.profile_name}>{user}</div>
          <div className={styles.profile_address}>
            {address}
            <span>
              <ContentCopyIcon
                onClick={(e) => {
                  //increate size of icon using e
                  (e.target as any).style.transition = "all 0.1s ease";
                  (e.target as any).style.fontSize = "2rem";
                  navigator.clipboard.writeText(address as any as string);
                  setTimeout(() => {
                    (e.target as any).style.fontSize = "1.5rem";
                  }, 100);
                }}
              />
            </span>
          </div>

          <div className={styles.create}>
                <div>Create <AddIcon /> </div>
          </div>
        </div>

        <div className={styles.chama}>
          <div className={styles.header}>
            <div className={styles.search}>
              <input type="text" placeholder="Search" />
            </div>
            <div className={styles.choose}>
              <div>Yours</div>
              <div>Others</div>
            </div>
          </div>
          <div className={styles.mine}></div>
          <div className={styles.all}></div>
        </div>
      </main>
    </>
  );
}

