
import Head from 'next/head'
import homeStyles from '@/styles/Home.module.css'
import Logo from './components/logo'


export default function Landing() {
    return (
        <>
            <Head>
                <title>Chama DAO</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={homeStyles.main}>
                <Logo />
                </main>
                </>
    )
}


