import { Inter } from "next/font/google"
import styles from "@/styles/Login.module.css"
import homeStyles from "@/styles/Home.module.css"
import Head from "next/head"
import Logo from "./components/logo"
import ArrowDownwardIcon from '@mui/icons-material/ArrowDownward';

const inter = Inter({ subsets: ["latin"] })

export default function SignUp() {
    return (
        <>
            <Head>
                <title>Chama DAO</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={homeStyles.main}>
                <Logo />
                <div className={`${styles.login} ${inter.className}`}>
                    <p className={styles.title}>We need to know who you are</p>
                    <p className={styles.title}>Please fill in the details below</p>
                    <p className={styles.title}><ArrowDownwardIcon /></p>
                    <div className={styles.form}>
                        <div className={styles.input}>
                            <label htmlFor="email">Email</label>
                            <input type="email" name="email" id="email" />
                            <p>What the input is about</p>
                        </div>
                        <div className={styles.input}>
                            <label htmlFor="email">Email</label>
                            <input type="email" name="email" id="email" />
                            <p>What the input is about</p>
                        </div>
                        <div className={styles.input}>
                            <label htmlFor="email">Email</label>
                            <input type="email" name="email" id="email" />
                            <p>What the input is about</p>
                        </div>
                        <button className={styles.button}>Login</button>
                    </div>
                </div>
            </main>
        </>
    )
}
