import { Inter } from "next/font/google";
import styles from "@/styles/Login.module.css";
import homeStyles from "@/styles/Home.module.css";
import Head from "next/head";
import Logo from "./components/logo";
import ArrowDownwardIcon from "@mui/icons-material/ArrowDownward";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function SignUp() {
  const [ethereum, setEthereum] = useState(null);
  const [account, setAccount] = useState(null);
  const [error, setError] = useState(false);

  useEffect(() => {
    if ((window as any).ethereum) {
        const data : any = window.localStorage.getItem('user')
        console.log(data)
        if(data){
            window.location.assign('/landing')
        }

      setEthereum((window as any).ethereum);
    } else {
      setError(true);
    }
  }, []);

  const connectWallet = async () => {
    try {
      const accounts = await (ethereum as any).request({
        method: "eth_requestAccounts",
      });
      const account = accounts[0];
      setAccount(account);
      console.log(account);
    } catch (error) {
      console.log(error);
    }
  };

  const handleInput = (e) => {
    e.preventDefault();
    const data = {
        username: e.target.username.value,
        address: account
    }
    console.log(data)
    //post data to backend
    window.localStorage.setItem('user', JSON.stringify(data))

    window.location.assign('/landing')
    };

  return (
    <>
      <Head>
        <title>Chama DAO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={homeStyles.main}>
        <Logo />
        <div className={`${styles.login} ${inter.className}`}>
          <p className={styles.title}>
            Before we continue, we would like you to choose a username, it will
            be used in place of your wallet address when your colleagues cannot
            remember it.
          </p>
          <div className={styles.form}>
            <form autoComplete="off" onSubmit={handleInput}>
              <div className={styles.input}>
                <input
                  autoComplete="false"
                  name="hidden"
                  type="text"
                  style={{ display: "none" }}
                />
                <label htmlFor="username">Username</label>
                <input
                  type="text"
                  name="username"
                  id="username"
                  autoComplete="false"
                  required
                />
                <p>Choose a username to help people identify you</p>
              </div>

              {error == true ? (
                <p className={styles.desc}>
                  You need to have metamask wallet on your browser to continue.
                  Please click{" "}
                  <a
                    href="https://metamask.io/download.html"
                    target="_blank"
                    style={{ color: "blue" }}
                  >
                    here
                  </a>{" "}
                  to download and configure, Thank you!
                </p>
              ) : (
                <>
                  {!account == true ? (
                    <>
                      <button
                        className={styles.connect}
                        onClick={() => connectWallet()}
                      >
                        Connect your wallet
                      </button>
                      <p className={styles.desc}>
                        You should have configured metamask on your browser
                        before clicking this button
                      </p>
                      <p className={styles.desc}>
                        If you have not, please click{" "}
                        <a
                          href="https://metamask.io/download.html"
                          target="_blank"
                          style={{ color: "blue" }}
                        >
                          here
                        </a>{" "}
                        to download metamask
                      </p>
                    </>
                  ) : (
                    <>
                      <br />
                      <br />
                      <p>{account}</p>
                    </>
                  )}
                  <br />
                  <br />
                  <br />
                  <br />

                  <p className={styles.desc}>
                    By clicking <b>Join Now</b> you agree to our{" "}
                    <a
                      href="https://metamask.io/download.html"
                      target="_blank"
                      style={{ color: "blue" }}
                    >
                      Terms of Service
                    </a>{" "}
                    and{" "}
                    <a
                      href="https://metamask.io/download.html"
                      target="_blank"
                      style={{ color: "blue" }}
                    >
                      Privacy Policy
                    </a>
                  </p>

                  <button className={styles.button}>Join Now</button>
                </>
              )}
            </form>
          </div>
        </div>
      </main>
    </>
  );
}
